spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        cache:
          missing_cache_strategy: create
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
  cache:
    ehcache:
      config: classpath:ehcache.xml
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 86400000 #a day
      refresh-token:
        expiration: 604800000 #7 days

minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: password123

cron:
  expression: "0 0 0 * * *"

url:
  stream:
    overwatch: https://www.twitch.tv/fefegg
    marvel-rivals: https://www.twitch.tv/lunium

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/teampeps
    username: ${DB_USERNAME}
    password: ${DB_USERNAME}

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: postgresql