spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        cache:
          missing_cache_strategy: create
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        javax:
          cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
  cache:
    ehcache:
      config: classpath:ehcache.xml
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: 86400000 #a day
      refresh-token:
        expiration: 604800000 #7 days
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}

cron:
  expression: "0 0 0 * * *"

url:
  stream:
    overwatch: https://www.twitch.tv/fefegg
    marvel-rivals: https://www.twitch.tv/lunium

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    hikari:
      max-lifetime: 1800000
      connection-timeout: 30000
      idle-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: info
    org.springframework.web: warn
    org.hibernate: error
    fr.teampeps: info

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect