INSERT INTO heroes (id, name, game, role, image_key) VALUES
                                                       (gen_random_uuid(), 'Ana', 'Overwatch', 'SUPPORT', 'heroes/overwatch/ana.png'),
                                                       (gen_random_uuid(), 'Ashe', 'Overwatch', 'DAMAGE', 'heroes/overwatch/ashe.png'),
                                                       (gen_random_uuid(), 'Baptiste', 'Overwatch', 'SUPPORT', 'heroes/overwatch/baptiste.png'),
                                                       (gen_random_uuid(), 'Bastion', 'Overwatch', 'DAMAGE', 'heroes/overwatch/bastion.png'),
                                                       (gen_random_uuid(), 'Brigitte', 'Overwatch', 'SUPPORT', 'heroes/overwatch/brigitte.png'),
                                                       (gen_random_uuid(), 'Cassidy', 'Overwatch', 'DAMAGE', 'heroes/overwatch/cassidy.png'),
                                                       (gen_random_uuid(), 'Doomfist', 'Overwatch', 'TANK', 'heroes/overwatch/doomfist.png'),
                                                       (gen_random_uuid(), 'D.Va', 'Overwatch', 'TANK', 'heroes/overwatch/dva.png'),
                                                       (gen_random_uuid(), 'Echo', 'Overwatch', 'DAMAGE', 'heroes/overwatch/echo.png'),
                                                       (gen_random_uuid(), 'Genji', 'Overwatch', 'DAMAGE', 'heroes/overwatch/genji.png'),
                                                       (gen_random_uuid(), 'Hanzo', 'Overwatch', 'DAMAGE', 'heroes/overwatch/hanzo.png'),
                                                       (gen_random_uuid(), 'Hazard', 'Overwatch', 'TANK', 'heroes/overwatch/hazard.png'),
                                                       (gen_random_uuid(), 'Illari', 'Overwatch', 'SUPPORT', 'heroes/overwatch/illari.png'),
                                                       (gen_random_uuid(), 'Junker Queen', 'Overwatch', 'TANK', 'heroes/overwatch/junker_queen.png'),
                                                       (gen_random_uuid(), 'Junkrat', 'Overwatch', 'DAMAGE', 'heroes/overwatch/junkrat.png'),
                                                       (gen_random_uuid(), 'Juno', 'Overwatch', 'SUPPORT', 'heroes/overwatch/juno.png'),
                                                       (gen_random_uuid(), 'Kiriko', 'Overwatch', 'SUPPORT', 'heroes/overwatch/kiriko.png'),
                                                       (gen_random_uuid(), 'Lifeweaver', 'Overwatch', 'SUPPORT', 'heroes/overwatch/lifeweaver.png'),
                                                       (gen_random_uuid(), 'Lúcio', 'Overwatch', 'SUPPORT', 'heroes/overwatch/lucio.png'),
                                                       (gen_random_uuid(), 'Mauga', 'Overwatch', 'TANK', 'heroes/overwatch/mauga.png'),
                                                       (gen_random_uuid(), 'Mei', 'Overwatch', 'DAMAGE', 'heroes/overwatch/mei.png'),
                                                       (gen_random_uuid(), 'Mercy', 'Overwatch', 'SUPPORT', 'heroes/overwatch/mercy.png'),
                                                       (gen_random_uuid(), 'Moira', 'Overwatch', 'SUPPORT', 'heroes/overwatch/moira.png'),
                                                       (gen_random_uuid(), 'Orisa', 'Overwatch', 'TANK', 'heroes/overwatch/orisa.png'),
                                                       (gen_random_uuid(), 'Pharah', 'Overwatch', 'DAMAGE', 'heroes/overwatch/pharah.png'),
                                                       (gen_random_uuid(), 'Ramattra', 'Overwatch', 'TANK', 'heroes/overwatch/ramattra.png'),
                                                       (gen_random_uuid(), 'Reaper', 'Overwatch', 'DAMAGE', 'heroes/overwatch/reaper.png'),
                                                       (gen_random_uuid(), 'Reinhardt', 'Overwatch', 'TANK', 'heroes/overwatch/reinhardt.png'),
                                                       (gen_random_uuid(), 'Roadhog', 'Overwatch', 'TANK', 'heroes/overwatch/roadhog.png'),
                                                       (gen_random_uuid(), 'Sigma', 'Overwatch', 'TANK', 'heroes/overwatch/sigma.png'),
                                                       (gen_random_uuid(), 'Sojourn', 'Overwatch', 'DAMAGE', 'heroes/overwatch/sojourn.png'),
                                                       (gen_random_uuid(), 'Soldier: 76', 'Overwatch', 'DAMAGE', 'heroes/overwatch/soldier_76.png'),
                                                       (gen_random_uuid(), 'Sombra', 'Overwatch', 'DAMAGE', 'heroes/overwatch/sombra.png'),
                                                       (gen_random_uuid(), 'Symmetra', 'Overwatch', 'DAMAGE', 'heroes/overwatch/symmetra.png'),
                                                       (gen_random_uuid(), 'Torbjörn', 'Overwatch', 'DAMAGE', 'heroes/overwatch/torbjorn.png'),
                                                       (gen_random_uuid(), 'Tracer', 'Overwatch', 'DAMAGE', 'heroes/overwatch/tracer.png'),
                                                       (gen_random_uuid(), 'Venture', 'Overwatch', 'DAMAGE', 'heroes/overwatch/venture.png'),
                                                       (gen_random_uuid(), 'Widowmaker', 'Overwatch', 'DAMAGE', 'heroes/overwatch/widowmaker.png'),
                                                       (gen_random_uuid(), 'Winston', 'Overwatch', 'TANK', 'heroes/overwatch/winston.png'),
                                                       (gen_random_uuid(), 'Wrecking Ball', 'Overwatch', 'TANK', 'heroes/overwatch/wrecking_ball.png'),
                                                       (gen_random_uuid(), 'Zarya', 'Overwatch', 'TANK', 'heroes/overwatch/zarya.png'),
                                                       (gen_random_uuid(), 'Zenyatta', 'Overwatch', 'SUPPORT', 'heroes/overwatch/zenyatta.png'),

                                                       (gen_random_uuid(), 'Captain America', 'Marvel Rivals', 'Vanguard', 'heroes/overwatch/captain_america.png'),
                                                       (gen_random_uuid(), 'Doctor Strange', 'Marvel Rivals', 'Vanguard', 'heroes/overwatch/doctor_strange.png'),
                                                       (gen_random_uuid(), 'Groot', 'Marvel Rivals', 'Vanguard', 'heroes/overwatch/groot.png'),
                                                       (gen_random_uuid(), 'Hulk', 'Marvel Rivals', 'Vanguard', 'heroes/overwatch/hulk.png'),
                                                       (gen_random_uuid(), 'Magneto', 'Marvel Rivals', 'Vanguard', 'heroes/overwatch/magneto.png'),
                                                       (gen_random_uuid(), 'Peni Parker', 'Marvel Rivals', 'Vanguard', 'heroes/overwatch/peni_parker.png'),
                                                       (gen_random_uuid(), 'The Thing', 'Marvel Rivals', 'Vanguard', 'heroes/overwatch/the_thing.png'),
                                                       (gen_random_uuid(), 'Thor', 'Marvel Rivals', 'Vanguard', 'heroes/overwatch/thor.png'),
                                                       (gen_random_uuid(), 'Venom', 'Marvel Rivals', 'Vanguard', 'heroes/overwatch/venom.png'),
                                                       (gen_random_uuid(), 'Venom', 'Marvel Rivals', 'Duelist', 'heroes/overwatch/venom.png'),
                                                       (gen_random_uuid(), 'Black Panther', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/black_panther.png'),
                                                       (gen_random_uuid(), 'Black Widow', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/black_widow.png'),
                                                       (gen_random_uuid(), 'Hawkeye', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/hawkeye.png'),
                                                       (gen_random_uuid(), 'Hela', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/hela.png'),
                                                       (gen_random_uuid(), 'Human Torch', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/human_torch.png'),
                                                       (gen_random_uuid(), 'Iron Fist', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/iron_fist.png'),
                                                       (gen_random_uuid(), 'Iron Man', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/iron_man.png'),
                                                       (gen_random_uuid(), 'Magik', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/magik.png'),
                                                       (gen_random_uuid(), 'Mister Fantastic', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/mister_fantastic.png'),
                                                       (gen_random_uuid(), 'Moon Knight', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/moon_knight.png'),
                                                       (gen_random_uuid(), 'Namor', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/namor.png'),
                                                       (gen_random_uuid(), 'Psylocke', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/psylocke.png'),
                                                       (gen_random_uuid(), 'Scarlet Witch', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/scarlet_witch.png'),
                                                       (gen_random_uuid(), 'Spider-Man', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/spider_man.png'),
                                                       (gen_random_uuid(), 'Squirrel Girl', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/squirrel_girl.png'),
                                                       (gen_random_uuid(), 'Star-Lord', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/star_lord.png'),
                                                       (gen_random_uuid(), 'Storm', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/storm.png'),
                                                       (gen_random_uuid(), 'The Punisher', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/the_punisher.png'),
                                                       (gen_random_uuid(), 'Winter Soldier', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/winter_soldier.png'),
                                                       (gen_random_uuid(), 'Wolverine', 'Marvel Rivals', 'DUELIST', 'heroes/marvel-rivals/wolverine.png'),
                                                       (gen_random_uuid(), 'Adam Warlock', 'Marvel Rivals', 'STRATEGIST', 'heroes/marvel-rivals/adam_warlock.png'),
                                                       (gen_random_uuid(), 'Cloak & Dagger', 'Marvel Rivals', 'STRATEGIST', 'heroes/marvel-rivals/cloak_dagger.png'),
                                                       (gen_random_uuid(), 'Invisible Woman', 'Marvel Rivals', 'STRATEGIST', 'heroes/marvel-rivals/invisible_woman.png'),
                                                       (gen_random_uuid(), 'Jeff the Land Shark', 'Marvel Rivals', 'STRATEGIST', 'heroes/marvel-rivals/jeff_the_land_shark.png'),
                                                       (gen_random_uuid(), 'Loki', 'Marvel Rivals', 'STRATEGIST', 'heroes/marvel-rivals/loki.png'),
                                                       (gen_random_uuid(), 'Luna Snow', 'Marvel Rivals', 'STRATEGIST', 'heroes/marvel-rivals/luna_snow.png'),
                                                       (gen_random_uuid(), 'Mantis', 'Marvel Rivals', 'STRATEGIST', 'heroes/marvel-rivals/mantis.png'),
                                                       (gen_random_uuid(), 'Rocket Raccoon', 'Marvel Rivals', 'STRATEGIST', 'heroes/marvel-rivals/rocket_raccoon.png');


