INSERT INTO heroes (id, name, game, role, image_key) VALUES
                                                       (gen_random_uuid(), 'Ana', 'OVERWATCH', 'SUPPORT', 'heroes/overwatch/ana.png'),
                                                       (gen_random_uuid(), 'Ashe', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/ashe.png'),
                                                       (gen_random_uuid(), 'Baptiste', 'OVERWATCH', 'SUPPORT', 'heroes/overwatch/baptiste.png'),
                                                       (gen_random_uuid(), 'Bastion', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/bastion.png'),
                                                       (gen_random_uuid(), 'Brigitte', 'OVERWATCH', 'SUPPORT', 'heroes/overwatch/brigitte.png'),
                                                       (gen_random_uuid(), 'Cassidy', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/cassidy.png'),
                                                       (gen_random_uuid(), 'Doomfist', 'OVERWATCH', 'TANK', 'heroes/overwatch/doomfist.png'),
                                                       (gen_random_uuid(), 'D.Va', 'OVERWATCH', 'TANK', 'heroes/overwatch/dva.png'),
                                                       (gen_random_uuid(), 'Echo', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/echo.png'),
                                                       (gen_random_uuid(), 'Genji', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/genji.png'),
                                                       (gen_random_uuid(), 'Hanzo', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/hanzo.png'),
                                                       (gen_random_uuid(), 'Hazard', 'OVERWATCH', 'TANK', 'heroes/overwatch/hazard.png'),
                                                       (gen_random_uuid(), 'Illari', 'OVERWATCH', 'SUPPORT', 'heroes/overwatch/illari.png'),
                                                       (gen_random_uuid(), 'Freja', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/freja.png'),
                                                       (gen_random_uuid(), 'Junker Queen', 'OVERWATCH', 'TANK', 'heroes/overwatch/junker_queen.png'),
                                                       (gen_random_uuid(), 'Junkrat', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/junkrat.png'),
                                                       (gen_random_uuid(), 'Juno', 'OVERWATCH', 'SUPPORT', 'heroes/overwatch/juno.png'),
                                                       (gen_random_uuid(), 'Kiriko', 'OVERWATCH', 'SUPPORT', 'heroes/overwatch/kiriko.png'),
                                                       (gen_random_uuid(), 'Lifeweaver', 'OVERWATCH', 'SUPPORT', 'heroes/overwatch/lifeweaver.png'),
                                                       (gen_random_uuid(), 'Lúcio', 'OVERWATCH', 'SUPPORT', 'heroes/overwatch/lucio.png'),
                                                       (gen_random_uuid(), 'Mauga', 'OVERWATCH', 'TANK', 'heroes/overwatch/mauga.png'),
                                                       (gen_random_uuid(), 'Mei', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/mei.png'),
                                                       (gen_random_uuid(), 'Mercy', 'OVERWATCH', 'SUPPORT', 'heroes/overwatch/mercy.png'),
                                                       (gen_random_uuid(), 'Moira', 'OVERWATCH', 'SUPPORT', 'heroes/overwatch/moira.png'),
                                                       (gen_random_uuid(), 'Orisa', 'OVERWATCH', 'TANK', 'heroes/overwatch/orisa.png'),
                                                       (gen_random_uuid(), 'Pharah', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/pharah.png'),
                                                       (gen_random_uuid(), 'Ramattra', 'OVERWATCH', 'TANK', 'heroes/overwatch/ramattra.png'),
                                                       (gen_random_uuid(), 'Reaper', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/reaper.png'),
                                                       (gen_random_uuid(), 'Reinhardt', 'OVERWATCH', 'TANK', 'heroes/overwatch/reinhardt.png'),
                                                       (gen_random_uuid(), 'Roadhog', 'OVERWATCH', 'TANK', 'heroes/overwatch/roadhog.png'),
                                                       (gen_random_uuid(), 'Sigma', 'OVERWATCH', 'TANK', 'heroes/overwatch/sigma.png'),
                                                       (gen_random_uuid(), 'Sojourn', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/sojourn.png'),
                                                       (gen_random_uuid(), 'Soldier: 76', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/soldier_76.png'),
                                                       (gen_random_uuid(), 'Sombra', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/sombra.png'),
                                                       (gen_random_uuid(), 'Symmetra', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/symmetra.png'),
                                                       (gen_random_uuid(), 'Torbjörn', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/torbjorn.png'),
                                                       (gen_random_uuid(), 'Tracer', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/tracer.png'),
                                                       (gen_random_uuid(), 'Venture', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/venture.png'),
                                                       (gen_random_uuid(), 'Widowmaker', 'OVERWATCH', 'DAMAGE', 'heroes/overwatch/widowmaker.png'),
                                                       (gen_random_uuid(), 'Winston', 'OVERWATCH', 'TANK', 'heroes/overwatch/winston.png'),
                                                       (gen_random_uuid(), 'Wrecking Ball', 'OVERWATCH', 'TANK', 'heroes/overwatch/wrecking_ball.png'),
                                                       (gen_random_uuid(), 'Zarya', 'OVERWATCH', 'TANK', 'heroes/overwatch/zarya.png'),
                                                       (gen_random_uuid(), 'Zenyatta', 'OVERWATCH', 'SUPPORT', 'heroes/overwatch/zenyatta.png');
INSERT INTO heroes (id, name, game, role, image_key) VALUES

                                                       (gen_random_uuid(), 'Captain America', 'MARVEL_RIVALS', 'VANGUARD', 'heroes/marvel-rivals/captain_america.webp'),
                                                       (gen_random_uuid(), 'Doctor Strange', 'MARVEL_RIVALS', 'VANGUARD', 'heroes/marvel-rivals/doctor_strange.webp'),
                                                       (gen_random_uuid(), 'Groot', 'MARVEL_RIVALS', 'VANGUARD', 'heroes/marvel-rivals/groot.webp'),
                                                       (gen_random_uuid(), 'Hulk', 'MARVEL_RIVALS', 'VANGUARD', 'heroes/marvel-rivals/hulk.webp'),
                                                       (gen_random_uuid(), 'Magneto', 'MARVEL_RIVALS', 'VANGUARD', 'heroes/marvel-rivals/magneto.webp'),
                                                       (gen_random_uuid(), 'Peni Parker', 'MARVEL_RIVALS', 'VANGUARD', 'heroes/marvel-rivals/peni_parker.webp'),
                                                       (gen_random_uuid(), 'The Thing', 'MARVEL_RIVALS', 'VANGUARD', 'heroes/marvel-rivals/the_thing.webp'),
                                                       (gen_random_uuid(), 'Thor', 'MARVEL_RIVALS', 'VANGUARD', 'heroes/marvel-rivals/thor.webp'),
                                                       (gen_random_uuid(), 'Venom', 'MARVEL_RIVALS', 'VANGUARD', 'heroes/marvel-rivals/venom.webp'),
                                                       (gen_random_uuid(), 'Venom', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/venom.webp'),
                                                       (gen_random_uuid(), 'Black Panther', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/black_panther.webp'),
                                                       (gen_random_uuid(), 'Black Widow', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/black_widow.webp'),
                                                       (gen_random_uuid(), 'Hawkeye', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/hawkeye.webp'),
                                                       (gen_random_uuid(), 'Hela', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/hela.png'),
                                                       (gen_random_uuid(), 'Human Torch', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/human_torch.webp'),
                                                       (gen_random_uuid(), 'Iron Fist', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/iron_fist.webp'),
                                                       (gen_random_uuid(), 'Iron Man', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/iron_man.webp'),
                                                       (gen_random_uuid(), 'Magik', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/magik.webp'),
                                                       (gen_random_uuid(), 'Mister Fantastic', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/mister_fantastic.webp'),
                                                       (gen_random_uuid(), 'Moon Knight', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/moon_knight.webp'),
                                                       (gen_random_uuid(), 'Namor', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/namor.webp'),
                                                       (gen_random_uuid(), 'Psylocke', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/psylocke.webp'),
                                                       (gen_random_uuid(), 'Scarlet Witch', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/scarlet_witch.webp'),
                                                       (gen_random_uuid(), 'Spider-Man', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/spider_man.webp'),
                                                       (gen_random_uuid(), 'Squirrel Girl', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/squirrel_girl.webp'),
                                                       (gen_random_uuid(), 'Star-Lord', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/star_lord.webp'),
                                                       (gen_random_uuid(), 'Storm', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/storm.webp'),
                                                       (gen_random_uuid(), 'The Punisher', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/the_punisher.webp'),
                                                       (gen_random_uuid(), 'Winter Soldier', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/winter_soldier.webp'),
                                                       (gen_random_uuid(), 'Wolverine', 'MARVEL_RIVALS', 'DUELIST', 'heroes/marvel-rivals/wolverine.webp'),
                                                       (gen_random_uuid(), 'Adam Warlock', 'MARVEL_RIVALS', 'STRATEGIST', 'heroes/marvel-rivals/adam_warlock.webp'),
                                                       (gen_random_uuid(), 'Cloak & Dagger', 'MARVEL_RIVALS', 'STRATEGIST', 'heroes/marvel-rivals/cloak_dagger.webp'),
                                                       (gen_random_uuid(), 'Invisible Woman', 'MARVEL_RIVALS', 'STRATEGIST', 'heroes/marvel-rivals/invisible_woman.webp'),
                                                       (gen_random_uuid(), 'Jeff the Land Shark', 'MARVEL_RIVALS', 'STRATEGIST', 'heroes/marvel-rivals/jeff_the_land_shark.webp'),
                                                       (gen_random_uuid(), 'Loki', 'MARVEL_RIVALS', 'STRATEGIST', 'heroes/marvel-rivals/loki.webp'),
                                                       (gen_random_uuid(), 'Luna Snow', 'MARVEL_RIVALS', 'STRATEGIST', 'heroes/marvel-rivals/luna_snow.webp'),
                                                       (gen_random_uuid(), 'Mantis', 'MARVEL_RIVALS', 'STRATEGIST', 'heroes/marvel-rivals/mantis.webp'),
                                                       (gen_random_uuid(), 'Rocket Raccoon', 'MARVEL_RIVALS', 'STRATEGIST', 'heroes/marvel-rivals/rocket_raccoon.webp');


