INSERT INTO maps (id, name, type, game, image_key ) VALUES
                                     (gen_random_uuid(), 'Antarctic Peninsula', 'CONTROL', 'Overwatch', 'maps/overwatch/antarctic_peninsula.png'),
                                     (gen_random_uuid(), 'Blizzard World', 'HYBRID', 'Overwatch', 'maps/overwatch/blizzard_world.png'),
                                     (gen_random_uuid(), 'Busan', 'CONTROL', 'Overwatch', 'maps/overwatch/busan.png'),
                                     (gen_random_uuid(), 'Circuit Royal', 'ESCORT', 'Overwatch', 'maps/overwatch/circuit_royal.png'),
                                     (gen_random_uuid(), 'Colosseo', 'PUSH', 'Overwatch', 'maps/overwatch/colosseo.png'),
                                     (gen_random_uuid(), 'Dorado', 'ESCORT', 'Overwatch', 'maps/overwatch/dorado.png'),
                                     (gen_random_uuid(), 'Eichenwalde', 'HYBRID', 'Overwatch', 'maps/overwatch/eichenwalde.png'),
                                     (gen_random_uuid(), 'Esperança', 'PUSH', 'Overwatch', 'maps/overwatch/esperanca.png'),
                                     (gen_random_uuid(), 'Gibraltar', 'ESCORT', 'Overwatch', 'maps/overwatch/gibraltar.png'),
                                     (gen_random_uuid(), 'Havana', 'ESCORT', 'Overwatch', 'maps/overwatch/havana.png'),
                                     (gen_random_uuid(), 'Hollywood', 'HYBRID', 'Overwatch', 'maps/overwatch/hollywood.png'),
                                     (gen_random_uuid(), 'Ilios', 'CONTROL', 'Overwatch', 'maps/overwatch/ilios.png'),
                                     (gen_random_uuid(), 'Junkertown', 'ESCORT', 'Overwatch', 'maps/overwatch/junkertown.png'),
                                     (gen_random_uuid(), 'King’s Row', 'HYBRID', 'Overwatch', 'maps/overwatch/kings_row.png'),
                                     (gen_random_uuid(), 'Lijiang Tower', 'CONTROL', 'Overwatch', 'maps/overwatch/lijiang_tower.png'),
                                     (gen_random_uuid(), 'Midtown', 'HYBRID', 'Overwatch', 'maps/overwatch/midtown.png'),
                                     (gen_random_uuid(), 'Nepal', 'CONTROL', 'Overwatch', 'maps/overwatch/nepal.png'),
                                     (gen_random_uuid(), 'New Junk City', 'FLASHPOINT', 'Overwatch', 'maps/overwatch/new_junk_city.png'),
                                     (gen_random_uuid(), 'New Queen Street', 'CONTROL', 'Overwatch', 'maps/overwatch/new_queen_street.png'),
                                     (gen_random_uuid(), 'Numbani', 'HYBRID', 'Overwatch', 'maps/overwatch/numbani.png'),
                                     (gen_random_uuid(), 'Oasis', 'CONTROL', 'Overwatch', 'maps/overwatch/oasis.png'),
                                     (gen_random_uuid(), 'Paraíso', 'HYBRID', 'Overwatch', 'maps/overwatch/paraiso.png'),
                                     (gen_random_uuid(), 'Rialto', 'ESCORT', 'Overwatch', 'maps/overwatch/rialto.png'),
                                     (gen_random_uuid(), 'Route 66', 'ESCORT', 'Overwatch', 'maps/overwatch/route_66.png'),
                                     (gen_random_uuid(), 'Runasapi', 'PUSH', 'Overwatch', 'maps/overwatch/runasapi.png'),
                                     (gen_random_uuid(), 'Samoa', 'CONTROL', 'Overwatch', 'maps/overwatch/samoa.png'),
                                     (gen_random_uuid(), 'Shambali Monastery', 'ESCORT', 'Overwatch', 'maps/overwatch/shambali_monastery.png'),
                                     (gen_random_uuid(), 'Suravasa', 'FLASHPOINT', 'Overwatch', 'maps/overwatch/suravasa.png'),

                                     (gen_random_uuid(), 'Central Park', 'CONVERGENCE', 'Marvel Rivals', 'maps/marvel-rivals/central_park.png'),
                                     (gen_random_uuid(), 'Hall of Djalia', 'CONVERGENCE', 'Marvel Rivals', 'maps/marvel-rivals/hall_of_djalia.png'),
                                     (gen_random_uuid(), 'Symbiotic Surface', 'CONVERGENCE', 'Marvel Rivals', 'maps/marvel-rivals/symbiotic_surface.png'),
                                     (gen_random_uuid(), 'Shin-Shibuya', 'CONVERGENCE', 'Marvel Rivals', 'maps/marvel-rivals/shin_shibuya.png'),
                                     (gen_random_uuid(), 'Midtown', 'CONVOY', 'Marvel Rivals', 'maps/marvel-rivals/midtown.png'),
                                     (gen_random_uuid(), 'Spider-Islands', 'CONVOY', 'Marvel Rivals', 'maps/marvel-rivals/spider_islands.png'),
                                     (gen_random_uuid(), 'Yggdrasill Path', 'CONVOY', 'Marvel Rivals', 'maps/marvel-rivals/yggdrasill_path.png'),
                                     (gen_random_uuid(), 'Hells Heaven', 'DOMINATION', 'Marvel Rivals', 'maps/marvel-rivals/hells_heaven.png'),
                                     (gen_random_uuid(), 'Birnin TChalla', 'DOMINATION', 'Marvel Rivals', 'maps/marvel-rivals/birnin_tchalla.png'),
                                     (gen_random_uuid(), 'Royal Palace', 'DOMINATION', 'Marvel Rivals', 'maps/marvel-rivals/royal_palace.png');

