INSERT INTO maps (id, name, type, game, image_key ) VALUES
                                     (gen_random_uuid(), 'Antarctic Peninsula', 'CONTROL', 'overwatch', 'maps/overwatch/antarctic_peninsula.jpg'),
                                     (gen_random_uuid(), 'Blizzard World', 'HYBRID', 'overwatch', 'maps/overwatch/blizzard_world.jpg'),
                                     (gen_random_uuid(), 'Busan', 'CONTROL', 'overwatch', 'maps/overwatch/busan.jpg'),
                                     (gen_random_uuid(), 'Circuit Royal', 'ESCORT', 'overwatch', 'maps/overwatch/circuit_royal.jpg'),
                                     (gen_random_uuid(), 'Colosseo', 'PUSH', 'overwatch', 'maps/overwatch/colosseo.jpg'),
                                     (gen_random_uuid(), 'Dorado', 'ESCORT', 'overwatch', 'maps/overwatch/dorado.jpg'),
                                     (gen_random_uuid(), 'Eichenwalde', 'HYBRID', 'overwatch', 'maps/overwatch/eichenwalde.jpg'),
                                     (gen_random_uuid(), 'Esperança', 'PUSH', 'overwatch', 'maps/overwatch/esperanca.jpg'),
                                     (gen_random_uuid(), 'Gibraltar', 'ESCORT', 'overwatch', 'maps/overwatch/gibraltar.jpg'),
                                     (gen_random_uuid(), 'Havana', 'ESCORT', 'overwatch', 'maps/overwatch/havana.jpg'),
                                     (gen_random_uuid(), 'Hollywood', 'HYBRID', 'overwatch', 'maps/overwatch/hollywood.jpg'),
                                     (gen_random_uuid(), 'Ilios', 'CONTROL', 'overwatch', 'maps/overwatch/ilios.jpg'),
                                     (gen_random_uuid(), 'Junkertown', 'ESCORT', 'overwatch', 'maps/overwatch/junkertown.jpg'),
                                     (gen_random_uuid(), 'King’s Row', 'HYBRID', 'overwatch', 'maps/overwatch/kings_row.jpg'),
                                     (gen_random_uuid(), 'Lijiang Tower', 'CONTROL', 'overwatch', 'maps/overwatch/lijiang_tower.jpg'),
                                     (gen_random_uuid(), 'Midtown', 'HYBRID', 'overwatch', 'maps/overwatch/midtown.jpg'),
                                     (gen_random_uuid(), 'Nepal', 'CONTROL', 'overwatch', 'maps/overwatch/nepal.jpg'),
                                     (gen_random_uuid(), 'New Junk City', 'FLASHPOINT', 'overwatch', 'maps/overwatch/new_junk_city.jpg'),
                                     (gen_random_uuid(), 'New Queen Street', 'CONTROL', 'overwatch', 'maps/overwatch/new_queen_street.jpg'),
                                     (gen_random_uuid(), 'Numbani', 'HYBRID', 'overwatch', 'maps/overwatch/numbani.jpg'),
                                     (gen_random_uuid(), 'Oasis', 'CONTROL', 'overwatch', 'maps/overwatch/oasis.jpg'),
                                     (gen_random_uuid(), 'Paraíso', 'HYBRID', 'overwatch', 'maps/overwatch/paraiso.jpg'),
                                     (gen_random_uuid(), 'Rialto', 'ESCORT', 'overwatch', 'maps/overwatch/rialto.jpg'),
                                     (gen_random_uuid(), 'Route 66', 'ESCORT', 'overwatch', 'maps/overwatch/route_66.jpg'),
                                     (gen_random_uuid(), 'Runasapi', 'PUSH', 'overwatch', 'maps/overwatch/runasapi.jpg'),
                                     (gen_random_uuid(), 'Samoa', 'CONTROL', 'overwatch', 'maps/overwatch/samoa.jpg'),
                                     (gen_random_uuid(), 'Shambali Monastery', 'ESCORT', 'overwatch', 'maps/overwatch/shambali_monastery.jpg'),
                                     (gen_random_uuid(), 'Suravasa', 'FLASHPOINT', 'overwatch', 'maps/overwatch/suravasa.jpg'),

                                     (gen_random_uuid(), 'Central Park', 'CONVERGENCE', 'marvel-rivals', 'maps/marvel-rivals/central_park.webp'),
                                     (gen_random_uuid(), 'Hall of Djalia', 'CONVERGENCE', 'marvel-rivals', 'maps/marvel-rivals/hall_of_djalia.webp'),
                                     (gen_random_uuid(), 'Symbiotic Surface', 'CONVERGENCE', 'marvel-rivals', 'maps/marvel-rivals/symbiotic_surface.webp'),
                                     (gen_random_uuid(), 'Shin-Shibuya', 'CONVERGENCE', 'marvel-rivals', 'maps/marvel-rivals/shin_shibuya.webp'),
                                     (gen_random_uuid(), 'Midtown', 'CONVOY', 'marvel-rivals', 'maps/marvel-rivals/midtown.webp'),
                                     (gen_random_uuid(), 'Spider-Islands', 'CONVOY', 'marvel-rivals', 'maps/marvel-rivals/spider_islands.webp'),
                                     (gen_random_uuid(), 'Yggdrasill Path', 'CONVOY', 'marvel-rivals', 'maps/marvel-rivals/yggdrasill_path.webp'),
                                     (gen_random_uuid(), 'Hells Heaven', 'DOMINATION', 'marvel-rivals', 'maps/marvel-rivals/hells_heaven.webp'),
                                     (gen_random_uuid(), 'Birnin TChalla', 'DOMINATION', 'marvel-rivals', 'maps/marvel-rivals/birnin_tchalla.webp'),
                                     (gen_random_uuid(), 'Royal Palace', 'DOMINATION', 'marvel-rivals', 'maps/marvel-rivals/royal_palace.webp');

