releaseName: peps-api-dev
namespace: peps-dev

image:
  repository: serkox/peps-api
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  className: nginx
  host: apipeps.serkox.ovh

service:
  port: 80
  type: ClusterIP
  targetPort: 8080
  protocol: TCP
  name: http

replicaCount: 1

springProfile: dev