releaseName: peps-api-prod
namespace: peps-prod

image:
  repository: serkox/peps-api
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  className: nginx
  host: api.teampeps.fr

service:
  port: 80
  type: ClusterIP
  targetPort: 8080
  protocol: TCP
  name: http

replicaCount: 4

springProfile: prod