releaseName: peps-api-dev
namespace: peps-dev

image:
  repository: serkox/peps-api
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  className: nginx
  host: api.2.11.47.69.nip.io

service:
  port: 80
  type: ClusterIP
  targetPort: 8080
  protocol: TCP
  name: http

replicaCount: 1

springProfile: dev