name: Deploy existing Docker image with Helm

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
env:
  IMAGE_NAME: serkox/peps-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: 📥 Download image tag artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag

      - name: 📦 Read image tag
        id: read-tag
        run: |
          TAG=$(cat tag.txt)
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: 📦 Set variables based on environment
        id: set-vars
        run: |
          if [ "${{ github.event.inputs.environment }}" = "prod" ]; then
            echo "release_name=peps-api-prod" >> $GITHUB_OUTPUT
            echo "namespace=peps-prod" >> $GITHUB_OUTPUT
            echo "values_file=values-prod.yaml" >> $GITHUB_OUTPUT
          else
            echo "release_name=peps-api-dev" >> $GITHUB_OUTPUT
            echo "namespace=peps-dev" >> $GITHUB_OUTPUT
            echo "values_file=values-dev.yaml" >> $GITHUB_OUTPUT
          fi

      - name: 🚀 Deploy with Helm
        run: |
          helm upgrade --install ${{ steps.set-vars.outputs.release_name }} ./deploy \
            --namespace ${{ steps.set-vars.outputs.namespace }} \
            -f deploy/${{ steps.set-vars.outputs.values_file }}